language: php

git:
  depth: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "irc.freenode.net#le24eme"
    on_success: change
    on_failure: always
