# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.slugger:
        class: AppBundle\Utils\Slugger
        arguments: []

    app.mail.parser:
        class: AppBundle\Utils\MailParser
        arguments: [@lasso_mail_parser.part_factory]

    app.feed.parser:
        class: PicoFeed\Reader\Reader
        arguments: []

    app.manager.activity:
        class: AppBundle\Manager\ActivityManager
        arguments: [@doctrine.orm.entity_manager, @app.slugger]

    app.manager.importer:
        class: AppBundle\Manager\ImporterManager
        arguments: [[@app.importer.git, @app.importer.mail, @app.importer.feed, @app.importer.icalendar, @app.importer.caldav, @app.importer.github]]

    app.manager.filter:
        class: AppBundle\Manager\FilterManager
        arguments: [@doctrine.orm.entity_manager, @app.slugger]

    app.manager.source:
        class: AppBundle\Manager\SourceManager
        arguments: [@doctrine.orm.entity_manager, @app.slugger, @app.manager.importer]

    app.manager.main:
        class: AppBundle\Manager\MainManager
        arguments: [@app.manager.activity, @app.manager.importer, @app.manager.filter, @app.manager.source]

    app.importer.git:
        class: AppBundle\Importer\Git\GitImporter
        arguments: [@app.manager.activity, @doctrine.orm.entity_manager]

    app.importer.mail:
        class: AppBundle\Importer\Mail\MailImporter
        arguments: [@app.manager.activity, @doctrine.orm.entity_manager, @app.mail.parser]

    app.importer.feed:
        class: AppBundle\Importer\Feed\FeedImporter
        arguments: [@app.manager.activity, @doctrine.orm.entity_manager, @app.feed.parser]

    app.importer.icalendar:
        class: AppBundle\Importer\ICalendar\ICalendarImporter
        arguments: [@app.manager.activity, @doctrine.orm.entity_manager]

    app.importer.caldav:
        class: AppBundle\Importer\Caldav\CaldavImporter
        arguments: [@app.manager.activity, @doctrine.orm.entity_manager]

    app.importer.github:
        class: AppBundle\Importer\GithubRepository\GithubImporter
        arguments: [@app.manager.activity, @doctrine.orm.entity_manager]
