# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.slugger:
        class: AppBundle\Utils\Slugger
        arguments: []

    app.mail.parser:
        class: AppBundle\Utils\MailParser
        arguments: [@lasso_mail_parser.part_factory]

    app.feed.parser:
        class: PicoFeed\Reader\Reader
        arguments: []

    app.activity.manager:
        class: AppBundle\Activity\ActivityManager
        arguments: [@doctrine.orm.entity_manager, @app.slugger]

    app.importer.git:
        class: AppBundle\Importer\Git\GitImporter
        arguments: [@app.activity.manager, @doctrine.orm.entity_manager]

    app.importer.mail:
        class: AppBundle\Importer\Mail\MailImporter
        arguments: [@app.activity.manager, @doctrine.orm.entity_manager, @app.mail.parser]

    app.importer.feed:
        class: AppBundle\Importer\Feed\FeedImporter
        arguments: [@app.activity.manager, @doctrine.orm.entity_manager, @app.feed.parser]
