# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.slugger:
        class: AppBundle\Utils\Slugger
        arguments: []

    app.activity.manager:
        class: AppBundle\Activity\ActivityManager
        arguments: [@doctrine.orm.entity_manager, @app.slugger]

    app.importer.git:
        class: AppBundle\Importer\Git\Importer
        arguments: [@app.activity.manager, @doctrine.orm.entity_manager]
